### ISSUE TITLE
/rya/ renders incorrectly in Noto Sans Siddham

### ISSUE THREAD

**Issue by virtualvinodh** [notofonts/siddham#2]
/rya/ conjunct is incorrectly displayed in Noto Sans Siddham.

Expected:

![image](https://user-images.githubusercontent.com/1050975/173927846-7fcf63fb-e99f-4e4e-80fa-8bdc071eb1ee.png)

(Generated using Muktam Siddham)

Displayed:

![image](https://user-images.githubusercontent.com/1050975/173926976-ac5ab95b-16d1-48f1-b554-cc7181c0d0fe.png)

It appears to be generated by placing the  _ya-vattu_ underneath the _repha_. 

![image](https://user-images.githubusercontent.com/1050975/173927618-a64dbb57-208d-4b9b-9172-9fdf84de9564.png)

In fact, it should rather look like other _repha_-based conjuncts such as /rka/, /rta/ etc. 

![image](https://user-images.githubusercontent.com/1050975/173928298-ce1aade9-411a-4044-9119-4cf72aa8648f.png)

All the images above were generated in Chrome.

V

**Comment by simoncozens** [comment]
I can certainly put this back and make the more "regular" rya form a stylistic set. Cc @tosche for opinion, as he will know the models well.

**Comment by Tosche** [comment]
All of my evidences take the form of my imprementation.

![IMG_3548](https://user-images.githubusercontent.com/5482424/174869469-99e8b304-d374-47c7-ad2d-d8e3f6914861.jpeg)
From 梵字大鑑

![IMG_3549](https://user-images.githubusercontent.com/5482424/174869458-9c8be5a7-eb9d-4a7a-8a65-c10c8750fb3e.jpeg)
From 梵字大鑑

![IMG_3550](https://user-images.githubusercontent.com/5482424/174869527-8ad2e065-5517-4436-a6bb-f34ffa4e43c0.jpeg)
This one has a tiny little head, but the -ya part is clearly the sub-base form.
From 梵字講和

![IMG_3553](https://user-images.githubusercontent.com/5482424/174869635-6bf6b147-fc59-457b-a599-e5fe6affcc28.jpeg)
ryaa instead of rya
From 梵字 悉曇

![IMG_3551](https://user-images.githubusercontent.com/5482424/174869566-483c36cb-d84f-4787-b236-a12490aa28f9.jpeg)
From the same book as the above, but this one's rya and ryaa are quite different for some reason.
From 梵字 悉曇

![IMG_3552](https://user-images.githubusercontent.com/5482424/174869798-80243b55-fc2b-41e4-b631-8b4a1e781427.jpeg)
From 梵字必携

![スクリーンショット 2022-06-21 18 31 54](https://user-images.githubusercontent.com/5482424/174869996-adf5567f-3e0a-48a0-baff-ec6baad4d8c1.png)
Horyuji manuscript, the oldest surviving Siddham document, has rya with a slight hint of the head (marked green). It's also ryaa, but the elongation mark is attached to the tail.
Source: http://emuseum.nich.go.jp/detail?langId=ja&webView=null&content_base_id=100625&content_part_id=001&content_pict_id=004

![Siddham-Manuscript-of-Heart-Sutra](https://user-images.githubusercontent.com/5482424/174869960-ffeeb72a-653a-42fb-9ed6-12898d74e639.jpg)
Heart Sutra (marked green). It’s ryaa, with elongation mark on the head.
Source: https://www.endangeredalphabets.net/alphabets/siddham/

**Comment by virtualvinodh** [comment]
@simoncozens 

Muktam Siddham is usually correct. I checked again some of the Siddham books that I have. It appears that both the repha-form and ya-vattu forms occur in manuscripts. But it looks like the ya-vattu form is more frequent than the repha-form. A stylistic set would be acceptable in this case. My apologies. I should have double-checked with my books before raising the issue.

In any case, I think it should be the regular-ra with ya-vattu added. The stem is too short in the current rendering (which made it look as if it was a misrendering)

V

**Comment by mandel59** [comment]
I have written a blog about the two shapes of /rya/ in Siddham: https://mandel59.hateblo.jp/entry/2021/11/22/010807 (written in Japanese) The following is rough translation of the blog article.

According [悉曇文字のデータ化に関する諸問題 一大蔵経テキストデータベース化に伴う悉曇文字作成をめぐって一](https://chisan.or.jp/wp-content/uploads/2019/11/user-pdfD-gendaimikkyo-19pdf-14.pdf#page=6&zoom=auto,-25,1104), two shapes of /rya/ are used in Taishō Tripiṭaka:
<img width="1030" alt="スクリーンショット 2022-07-11 3 18 25" src="https://user-images.githubusercontent.com/1079715/178157171-a3ed0c9a-f2fe-4cd5-a62c-396eff7507e5.png">

> 2、「r〜」形の文字
> 　ローマ字表記上先頭に「r」が付く文字についても異体字が生じる。例えば「rya」は大正蔵中二種類の字体が存在する。一つは「ra」の切継上半体に「ya」を継いだもの、つまり悉曇十八章中の第八章の規則に従ったもの（<img width="27" alt="スクリーンショット 2022-07-11 3 26 02" src="https://user-images.githubusercontent.com/1079715/178157384-66181fd3-9b9b-4b6a-aa8b-ff128312ddef.png">）、もう一つは悉曇十八章中第二章の規則に従った「ra」の切継上半体に「ya」の切継下半体を継いだもの（<img width="28" alt="スクリーンショット 2022-07-11 3 26 06" src="https://user-images.githubusercontent.com/1079715/178157387-371e4891-791f-45c4-8996-0f19b34ca17f.png">）である。

> Characters beginning with /r/ also have variants. For example, two forms of /rya/ are used in Taishō Tripiṭaka: one (<img width="27" alt="スクリーンショット 2022-07-11 3 26 02" src="https://user-images.githubusercontent.com/1079715/178157384-66181fd3-9b9b-4b6a-aa8b-ff128312ddef.png">) is the upper half of /ra/ with /ya/, that follows the rule in chapter 8 of 悉曇十八章, and the other (<img width="28" alt="スクリーンショット 2022-07-11 3 26 06" src="https://user-images.githubusercontent.com/1079715/178157387-371e4891-791f-45c4-8996-0f19b34ca17f.png">) is the upper half of /ra/ with the lower half of /ya/, that follows the rule in chaper 2.

The Unicode standards doesn't describe how implement these two variants in Siddham script. That is problematic for implementing Unicode Siddham fonts.

On the other hand, other Brahmic scripts like Devanāgarī, Bengali and Kannada scripts also have variants of /rya/ and the Unicode standard describe on it as Alternative Forms of Cluster-Initial RA:

> **Alternative Forms of Cluster-Initial RA.** In addition to reph (rule R2) and eyelash (rule R5a), a cluster-initial RA may also take its nominal form while the following consonant takes a reduced form. This behavior is required by languages that make a morphological distinction between “reph on YA” and “RA with reduced YA”, such as Braj Bhasha. To trigger this behavior, a ZWJ is placed immediately before the virama to request a reduced form of the following consonant, while preventing the formation of reph, as shown in the third example below.
> Similar, special rendering behavior of cluster-initial RA is noted in other scripts of India. See, for example, “Interaction of Repha and Ya-phalaa” in Section 12.2, Bengali (Bangla), “Reph” in Section 12.7, Telugu, and “Consonant Clusters Involving RA” in Section 12.8, Kannada.

If we borrow the rules of other Indian scripts to Siddham script, it seems that the upper half of /ra/ with /ya/ (equivalent to "reph on YA") should be represented as ra + virama + ZWJ + ya, and the upper half of /ra/ with the lower half of /ya/ (equivalent to "RA with reduced YA") should be represented as ra + ZWJ + virama + ya. "RA with reduced YA") should be represented as ra + ZWJ + virama + ya, but such a behavior is not explicitly described for Siddham script, and there does not seem to be any font that implements it.

And there is also the issue of how to render /rya/ without ZWJ, which is unspecified.
